### ISSUE TITLE
False sense of security in select narrowing

### ISSUE THREAD

**Issue by EliLichtblau** [schummar/schummar-translate#24]
Hi again!

I was thinking about the implementation of select narrowing and what would happen if you passed in an unknown string from a function parameter. Here would be an example
```ts
type ICU = Parse<"{opt, select, abbr {{a}} other { {b} }}">
//.      ^? {opt: "abbr", a: Value} | {opt: string&{}, b: Value}

declare function takesICU(icu: ICU): void;

function caller(unknownString: string) {
    takesICU({
          opt: unknownString,
          b: "b"
          // we don't have to define "a" since "string" satisfies string&{}
    })
}

caller("abbr")// goes to "a" path but "a" will not be defined
```
Here's a playground link to the above code in case you want too look at it
[playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAaghgGwK7QLxQM7AE4EsB2A5lAD5T5IC2ARhNqVNQPZMIRz4MAicwEA3AChBoSFADqAC1x8MYOAGM0UAOSqGKgDrA1ZLfl2rN2FUMEB6AFSWoAJQiUmAN2hs4AEwLEO7qMDi4CF5QAO7SsvJKUJbmIuDQACp4lAA8CQB8UOgJUBAAHnz47hhQAAYAJADeUjIQcooQAL5VBABmdHZ1wI2lglBQAPxQSbip9ljpfVAAXMO5BRBFJRWVbR3j3VU1EQ09U0MjY12T-bM5+YXFmDhe+8NTs-gQLthmVjb2wEjY+CUcUHBsNg4CAoExWn4mGAoGwXAhGAgmAoANYlGJxMQAMQI7gAQoiURg0hdMtkLvNLssqlg8ERGpUWvh2vRbLhCJJuqUoOZzK0cVA+dgsFBKnd7B58UjkSkVCoADR2NkchWyzIXRZXADaa3okpRCp1wwCCAAulN+kNNXrkQqAHT27FFa1EhLG9Im7nmKDYdi+agE5EAooC-lPAoIqUCpj0fyBc0zcjPOgPKCak38T3kJgihU+r4-XKUMCgb11JAIYDCd5QR1+gMlVrR3KKSR+JBgNi5fA4UHo0SJdtsWvOtKkubqpaljxMfAIUHapkdbFC4B2+2GjYey3223D+spZcTNe2hKDiB7qVEjbuhNpt7WToePzGqBIbuBPySaAKb4+7tzsFIE4f1I1wEoFERDAIHcW1OnzThgC-CMUSgBQZ0KYAg18H1hXBZ8Pz7eJHzxAMUmtCkNRKGkvAVV0PwnK5qKIBUuAgYtWwYqibiIMc6PhTiykZZkoAAGQARkaZpVkXFkJK5HkQ2DQVhUaO5xIoycVkNESACZ6SE9Y9Pkr1cAhMAfSUaDoMYUFKgVRCwMAxY-kTLBrJAlF4yGcUSKlFIVmtKTdPpUoFRWWw9Kk2w5LCqpWPYxoAGpSkyBTEMWVD0IIFBMHYbAFFbPB2UwvCHJKUV+lOKB4sQjSrlKRKDJZLoekzCAECgqBTKgdw2NqzIAAYvOI61-KqQKqnEyTQrsMSFWvTN0s4Pl8DAr9fCeNy6ylBU0PfChoCgwECu9JUSohZTMNUyrbwCgMgpi2aPQU9rOrzb5lvLeEPMDHxcuO1tG3oMNKyqu9M3wbNGlzCB4MLYtsFBHDy0rCwHwABUBTqfphuGnEBXA4H9OpQhkVt+z+YMLO+DBcDhUEVo2rp3PrUmHM4QixExoUIFG60x3IgStJkqAADk4EoJo5Samto0oXhoZljY9gtYZkgPOXeDVBZJxUKC2AUHRhoAZXaiBDYAeWLXAZxddXxcl9JaPV68Tkq2ZKlTABpLrOEOFIHYgd1ZngPAibYBJ4jSdXMU14B0kyRooAAMmGM9uag0bTw7c8cRHC9CRSV23dmQWdfqmXA8V6ThNj7B5c5O5Pc1H2CDV0YA4loOTRDgnw4gSPIGjju64bhOoGuhNm9bv31f5nvYEQHLGnvGwM+gH6o3odgTq+HOux7aJYn7NOc-XrPeLqkofWnWd50NQ9VygHcNy6LcoHP0jH8yVPs7YT+-ILVmG+ZEkMQj4DMCfUOhNiaDwgGkK+1xaSEEvgJFQFAaB0EMCoDs3xEDYP1ubYA0ZPD4HwYMcgVBaD0DOIglQ7heAQGwcAUYTCKE8D4AmeAyABDCBPrWC2SA+DYE7pLRBTFCDzWOFkTowohYyxEhAVo3QGQ13WGdFWFCfKjVlPNM6KoVDa0pKmQ01oDQiz4maG6QwAAU09fZiy7gvAAEj4NgFt0oiP9oo5R48k6-3TljXmX8877n5ukAAlAwARQi6CiIgLRN08ZHhJmwCmJ4LxIFEVcUUdxnjRwyJUEwTxagBI5CGAAUTyBBJAvU0gqmKV+EwmQyA2IkSnEUjQolnCyWIU2BtgBWxYbbeJ4juKSNkfHGRMThHxKkRMXp0AKkYAUHASAIlcDImUKUFQVQVCVGwY0bBMoNDpBUD0IQJ9jY3DAMs1ZkAXSoPLlSNR9AfHdFlErDRvRVYrHeVFb5KZzjPMEq8qA1zASbEqHctZEANlbKkhIo5MsKlFE0UMFYELsBQuuXgW5KzYVElRe4dImjaHyLBViqFML1mbKaNScZ6LwX+GxUCy5RE-4QFxbgfF9y6gFOyIgm+7gZwAQXLXXAK5jyvywO-TU3LeWEoPJKo8z97ScoVTS-l14PSzDvFWB8ABhRAP4ECMMpmCagAArIhfgiIhDJgCBA8J8Zh2JpTXw6VJV2oeQ49KUBCB0wygASUNQAVS3g3JBwR0T5DANGTCJ8ADisNQ1hoAILYEIC6MZyCGDCtFaCCRaZeKBJ5qNKYwLjEFrvtGogaYKGcoLqiNIZ5NUEoeaOTIsxm1EnbXyx5kx0iLI-kElIuAfy5q8GOTEZrgCFBSCm4AabM3ZvHT+BOwgqxegALJwC2SUE+wr+4YmgLO3gC6MgyKrZRS1NrDYUIqqmdGDitkgDwgkBeCRNTozNEnHpW6T5ppkevFIAAiSoUIn6EMNgqIm1B6CVEqHASSYJPEihFNQJOkkwOTAUv0AAegMYQvUIKAmgK0N8hsbYIX3XUNNNiJ1IFmGmiJswnBMFwO4MwlH8DUZnKhRAbBsA2JAWA-A3KiCzAkVEp9-R-AHoY3Jm6lUoPAPwKApg4DJOSPjCpxgswwPUDA3plTCkQjQBFQYTCkg4AuEhD1JRBBoBgbgGBzABAohgYke5jAvAwJ8hJhI5OlRJ79C6YIVSghVnOroDY1z1AENgYiQpQgTASbEKgK59z8harUCEVltzpNnVZkwrQRzK1oJbqAA)

To get around this behavior I did a strong type brand on the other string so it can be reduced to, and then made another type which is essentially the merged types that make up the union. Now select returns "originalUnion | Merged<originalUnion>" 
```ts
/* New behavior */
type ICU = Parse<"{opt, select, abbr {{a}} other { {b} }}">
//.      ^? {opt: "abbr", a: Value} | {opt: string&{__other : "other"}, b: Value} | {opt: string&{}, a: Value, b: Value}

/* Implementation details */

/* Modified code */
// Change
type SelectOptions<Name extends string, Rest> = KeepAndMerge<FindOuter<Name, Rest>>;
// small helper
type KeepAndMerge<T extends object> = T | MergeTypeUnion<T>

// old: type HandleOther<T> = 'other' extends T ? Exclude<T, 'other'> | (string & {}) : T;
// new:
type HandleOther<T> = 'other' extends T ? Exclude<T, 'other'> | OtherString : T;


/* Added code */
// Specific other brand
type OtherString = string & {__other: "other"}

// Helpers to convert "A | B | C ..." -> single type of all members
type KeysFromUnion<T> = T extends T ? keyof T : never
type SimpleTypeMerge<T, K extends keyof any> = T extends {[k in K]?: any} ? 
  T[K] extends OtherString ? string & {} : T[K] : never
type MergeTypeUnion<T extends object> = {
  [k in KeysFromUnion<T>]: SimpleTypeMerge<T, k>
}


```

Heres the p[layground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAaghgGwK7QLxQM7AE4EsB2A5lAD5T5IC2ARhNqVNQPZMIRz4MAicwEA3AChBoSFADqAC1x8MYOAGM0UAOSqGKgDrA1ZLfl2rN2FUMEB6AFSWoAJQiUmAN2hs4AEwLEO7qMDi4CF5QAO7SsvJKUJbmIuDQACp4lAA8CQB8UOgJUBAAHnz47hhQAAYAJADeUjIQcooQAL5VBABmdHZ1wI2lglBQAPxQSbip9ljpfVAAXMO5BRBFJRWVbR3j3VU1EQ09U0MjY12T-bM5+YXFmDhe+8NTs-gQLthmVjb2wEjY+CUcUHBsNg4CAoExWn4mGAoGwXAhGAgmAoANYlGJxMQAMQI7gAQoiURg0hdMtkLvNLssqlg8ERGpUWvh2vRbLhCJJuqUoOZzK0cVA+dgsFBKnd7B58UjkSkVCoADR2NkchWyzIXRZXADaa3okpRCp1wwCCAAulN+kNNXrkQqAHT27FFa1EhLG9Im7nmKDYdi+agE5EAooC-lPAoIqUCpj0fyBc0zcjPOgPKCak38T3kJgihU+r4-XKUMCgb11JAIYDCd5QR1+gMlVrR3KKSR+JBgNi5fA4UHo0SJdtsWvOtKkubqpaljxMfAIUHapkdbFC4B2+2GjYey3223D+spZcTNe2hKDiB7qVEjbuhNpt7WToePzGqBIbuBPySaAKb4+7tzsFIE4f1I1wEoFERDAIHcW1OnzThgC-CMUSgBQZ0KYAg18H1hXBZ8Pz7eJHzxAMUmtCkNRKGkvAVV0PwnK5qKIBUuAgYtWwYqibiIMc6PhTiykZZkoAAGQARkaZpVkXFkJK5HkQ2DQVhUaO5xIoycVkNESACZ6SE9Y9Pkr1cAhMAfSUaDoMYUFKgVRCwMAxY-kTLBrJAlF4yGcUSKlFIVmtKTdPpUoFRWWw9Kk2w5LCqpWPYxoAGpSkyBTEMWVD0IIFBMHYbAFFbPB2UwvCHJKUV+lOKB4sQjSrlKRKDJZLoekzCAECgqBTKgdw2NqzIAAYvOI61-KqQKqnEyTQrsMSFWvTN0s4Pl8DAr9fCeNy6ylBU0PfChoCgwECu9JUSohZTMNUyrbwCgMgpi2aPQU9rOrzb5lvLeEPMDHxcuO1tG3oMNKyqu9M3wbNGlzCB4MLYtsFBHDy0rCwHwABUBTqfphuGnEBXA4H9OpQhkVt+z+YMLO+DBcDhUEVo2rp3PrUmHM4QixExoUIFG60x3IgStJkqAADk4EoJo5Samto0oXhoZljY9gtYZkgPOXeDVBZJxUKC2AUHRhoAZXaiBDYAeWLXAZxddXxcl9JaPV68Tkq2ZKlTABpLrOEOFIHYgd1ZngPAibYBJ4jSdXMU14B0kyRooAAMmGM9uag0bTw7c8cRHC9CRSV23dmQWdfqmXA8V6ThNj7B5c5O5Pc1H2CDV0YA4loOTRDgnw4gSPIGjju64bhOoGuhNm9bv31f5nvYEQHLGnvGwM+gH6o3odgTq+HOux7aJYn7NOc-XrPeLqkofWnWd50NQ9VygHcNy6LcoHP0jH8yVPs7YT+-ILVmG+ZEkMQj4DMCfUOhNiaDwgGkK+1xaSEEvgJFQFAaB0EMCoDs3xEDYP1ubYA0ZPD4HwYMcgVBaD0DOIglQ7heAQGwcAUYTCKE8D4AmeAyABDCBPrWC2SA+DYE7pLRBTFCDzWOFkTowohYyxEhAVo3QGQ13WGdFWFCfKjVlPNM6KoVDa0pKmQ01oDQiz4maG6QwAAU09fZiy7gvAAEj4NgFt0oiP9oo5R48k6-3TljXmX8877n5ukAAlAwARQi6CiIgLRN08ZHhJmwCmJ4LxIFEVcUUdxnjRwyJUEwTxagBI5CGAAUTyBBJAvU0gqmKV+EwmQyAeKacbbixAzhvC9AAYUkBwQgEAMTQFNgbYAVsWG23ieIzpUiJgyK9hANiABBIoABZOgQyDw4kEcI+J8z47pCEApDA8sEDwi-AgSAaST5LNWRsrZ8DzjlxKEwagAArIhl8yCbOwEMuBABVVaM5RzCBGVACpGAFBwEgCJXAyJlClBUFUFQlRsGNGwTKDQ6QVA9CECfDpeAwBQphZAF0qDXmCTUfQHx3RZRKw0b0VWKw6VRSZSmF5xjhbCQ6YCTYlRSWwogPCxFUkJGYplhUoomihgrD5dgAVRLcAkuhcKok0r3DpE0bQ+RNKoAKoFUKuFCKmjUk6bKg1-hFWcoJURP+EBlWqrJXUAp2REE33cDOACC5a64BXMeV+WB36aidca1139jwOrDWq8lRdjgelmHeKsD5emIB-AgRhlMwSfKIX4IiIQyYAguVAfGYdiaU18Olf1+byUOPSlAQgdMMoAElemAq3g3JBwR0T5DANGTCJ8ADisM22ApWf8l0szkEME9d60EEi0y8UCTzUaUwuWUSnF6u+3aiBpgoQ6guqI0hnhjS6ilmRZhHqJGe9Vo5JjHL4URdeKRcA-mnV4McmJM3AEKCkEdwAx0TsIESN9SAE5PrEGhIsbA8gyJfQAIkqFCJ+hDDYKiJtQeglRKhwEkmCTxIoRTUCTpJBDkwFL9AAHoDHBWjMWEAQhQGce1G5aJYgKXWXARFJQT6ev7hC79vA-0ZBkRuyc7yvmGwoRVVM6MHGIpAHhBIC8EianRmaJO3SLBemNpABQpk30EaaYwYERQIVtLoMqogMiJEpxFAAfQc40ugswEMuewAh1SEKlkgAwJibATBKDAptvgN144qXlKgIp5TCYMnJkJaMHOcC-nbISAqH2AkYsQg4CASlxjKiakDG3L2JoBizFy0nIY66W4egEpZ7A1niBDDs6nSoWnhi1bi6kiFqWB7xBC6C8TVxJPfJkbJorDjfP+cC8FkFYWMgL2NkliO8Q+v1Oi5MbzdGIVjvg0ElISGUMKjQ0-TD2HcP4Y80RyoJGJ6NHIzpyqNHhC9QgoCaArQ3yG1C8+HjY6bFgdmGOiJswnBMFwO4MwX38A-ZnKhRAbBsA2JAWA-ATXZgSKibJ-o-h-vtrsfGG6-QUPAPwKApg4CmtyiJ8T6gbnqAIdpzdBSIRoDbpUJhAZLhIQ9SUQQaACG4AIawp+Ryjk4C1ugHQQL2BpgRPjI0BX3mYUXLoDYoX1AsMIYiQpQgTASbEKgELkX8harUCEcb4XpMS2Q0wrQPnK1oJAA)

Now the above example errors which I think is more desirable behavior but your choice! Sorry for opening so many issues, thank you for the library!

**Comment by schummar** [comment]
True. I wanted to avoid the explicit cast to `OtherString`, but you are right, that doesn't catch many potential errors.
The most common use case is likely passing a string and all parameters anyway, so no real loss.

Thanks for the work, I mostly could use your code as is and only added some tests.
