### ISSUE TITLE
Unable to resolve 'schummar-translate/react' since v1.21.0

### ISSUE THREAD

**Issue by alex-maxime** [schummar/schummar-translate#29]
Hello i was trying to test schummar translate on a react-native project with expo. and i have this error with all version >= 1.21
<img width="331" alt="Capture d’écran 2024-11-22 à 03 32 26" src="https://github.com/user-attachments/assets/b4a8bfc5-b528-4ffd-8942-2d93bce6a4fe">
I have notice that `react.js` & `react.d.ts` files are missing since v1.21.0
<img width="798" alt="Capture d’écran 2024-11-22 à 03 35 37" src="https://github.com/user-attachments/assets/eb11fcde-ba28-488d-8d61-7e62a24b160d">
<img width="798" alt="Capture d’écran 2024-11-22 à 03 36 02" src="https://github.com/user-attachments/assets/1a3e566b-b6e2-4736-873e-17da8122a361">

My current fix is to force v1.20.3

Thank you for your time on this lib

**Comment by schummar** [comment]
I assumed those legacy style export are not needed anymore. Node has been able to work with the package.json's exports field for a long time. But ok, maybe expo doesn't or you are using an old version of node.

Anyway, I have added it again. Please try version 1.21.4

**Comment by alex-maxime** [comment]
thank you. i will try this.
I Am using `node v20.18.0`, maybe the it is because on expo we use babel, or metro bundler 🧐
